"""Initial migration with PII encryption

Revision ID: bdf5f1265a5c
Revises: 
Create Date: 2025-08-14 16:34:14.162980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf5f1265a5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enable the pgcrypto extension required for encryption functions
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    op.create_table('jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('input_hash', sa.String(length=128), nullable=False),
        sa.Column('result', sa.LargeBinary(), nullable=True),
        sa.Column('cost', sa.Float(), nullable=True),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_input_hash', 'jobs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index('ix_jobs_input_hash', table_name='jobs')
    op.drop_table('jobs')

    # Drop the pgcrypto extension
    op.execute("DROP EXTENSION IF EXISTS pgcrypto;")
    # ### end Alembic commands ###
