NODE_ENV: production
NEXT_TELEMETRY_DISABLED: "1"
INTERNAL_API_BASE_URL: https://api.restailor.com
NEXT_PUBLIC_API_BASE_URL: https://api.restailor.com
NEXT_PUBLIC_API_URL: https://api.restailor.com
NEXT_PUBLIC_SITE_URL: https://restailor.com
NEXT_PUBLIC_FEATURE_ANALYTICS: "1"
NEXT_PUBLIC_SUPPORT_EMAIL: support@restailor.com
NEXT_PUBLIC_TURNSTILE_SITE_KEY: "0x4AAAAAACADoTLZH7pI8MiR"
NEXT_PUBLIC_GTAG_ID: ""
